# runtime: python27
# api_version: 1
# threadsafe: true
# handlers:
# - url: /
#   static_files: dist/djangular-front/index.html
#   upload: dist/djangular-front/index.html
# - url: /
#   static_dir: dist/djangular-front

runtime: nodejs8